### ISSUE TITLE
Cannot download Samsung watch updates

### ISSUE THREAD

**Issue by techyminati** [martinetd/samloader#9]
## Description
The tool cannot fetch Galaxy Watch 4 fw

## Reproduction Steps
samloader -m SM-R890 -r INS -i XXXXXXXXXXXXXXX checkupdate
R890XXU1HWL1/R890OXM1HWL3/R890XXU1HWL1/R890XXU1HWL1

works
but download fails
Traceback (most recent call last):
  File "/home/techyminati/.local/bin/samloader", line 8, in <module>
    sys.exit(main())
  File "/home/techyminati/.local/lib/python3.10/site-packages/samloader/main.py", line 43, in main
    path, filename, size = getbinaryfile(client, args.fw_ver, args.dev_model, args.dev_imei, args.dev_region)
  File "/home/techyminati/.local/lib/python3.10/site-packages/samloader/main.py", line 104, in getbinaryfile
    raise Exception("DownloadBinaryInform returned {}, firmware could not be found?".format(status))
Exception: DownloadBinaryInform returned 408, firmware could not be found?

## Output
Traceback (most recent call last):
  File "/home/techyminati/.local/bin/samloader", line 8, in <module>
    sys.exit(main())
  File "/home/techyminati/.local/lib/python3.10/site-packages/samloader/main.py", line 43, in main
    path, filename, size = getbinaryfile(client, args.fw_ver, args.dev_model, args.dev_imei, args.dev_region)
  File "/home/techyminati/.local/lib/python3.10/site-packages/samloader/main.py", line 104, in getbinaryfile
    raise Exception("DownloadBinaryInform returned {}, firmware could not be found?".format(status))
Exception: DownloadBinaryInform returned 408, firmware could not be found?

## Environment
Ubuntu 22.04 
Python 3.10.12

**Comment by martinetd** [comment]
You'll get that error if the imei/serial number isn't valid -- unfortunately that's not something I can help with unless you somehow give me your real SN (something that starts with RFxxxx), and you probably shouldn't share it with strangers, so not quite sure how to help.

(FWIW, the checkupdate command doesn't use it, so that it worked doesn't mean anything)


If you're sure you used a correct imei or SN then they might have changed something again, I don't have my normal PC with me to check; might want to have a look at https://github.com/zacharee/SamloaderKotlin or another reimplementation that's more actively maintained. But try to check if you use the correct SN first :)

**Comment by techyminati** [comment]
@martinetd I got the OTA link but it says Access Denied, I was able to extract key:pair value from OTA payload

**Comment by techyminati** [comment]
Link is here [URL](https://fota-s3-dn.ospserver.net/firmware/INS/SM-R890/4f191755ab53410a90a1b12b76e6f083.bin?px-hash=&px-wid=2777391-WCC240210073551&px-wctime=2024-02-10%2007:35:51&px-cc=INS&px-mn=SM-R890&Policy=eyJTdGF0ZW1lbnQiOiBbeyJSZXNvdXJjZSI6Imh0dHA6Ly9mb3RhLXMzLWRuLm9zcHNlcnZlci5uZXQvZmlybXdhcmUvSU5TL1NNLVI4OTAvNGYxOTE3NTVhYjUzNDEwYTkwYTFiMTJiNzZlNmYwODMuYmluP3B4LWhhc2g9JnB4LXdpZD0yNzc3MzkxLVdDQzI0MDIxMDA3MzU1MSZweC13Y3RpbWU9MjAyNC0wMi0xMCUyMDA3OjM1OjUxJnB4LWNjPUlOUyZweC1tbj1TTS1SODkwKiIsIkNvbmRpdGlvbiI6eyJEYXRlTGVzc1RoYW4iOnsiQVdTOkVwb2NoVGltZSI6MTcxMTAwNjU1NX19fV19&Signature=YUg88rNXIdvkiNrHWu9kE42xcMHDDIgsu~SKlMTJKOFn3Mre9c~2KAjGvu-OoMXfPple8-fD71e73C~ntJbzcCllBkAApHcXBvyQxnZb0tgTsTdvrdzDtHyCbyJfnp4CwznLu5nvyOZha0ewrA4MNhwFpEYwAiyHz5VCfNTHlG-SwHOEsOl4MOoJdUoHREpr99kUfnq96N4ZO5D4F3FvTw2nTi6iQgxmCpBN1eiA8eei1WwTj3iFSArSeRedLQ20ZCuZW8ycr5glGNMldh4pvxlrIUvgg7bngNSCmiCcRIhM8yGaHHp-mdni-ayYDsRIYR86i9FmcClEZIZKVmEWBA__&Key-Pair-Id=APKAIGLPRCHE2BH6RZLQ&px-nb=UGtezEZ854jbmFcvWGxLEA==)

**Comment by techyminati** [comment]
@martinetd do you have telegram? Maybe I can ping you there and share other details?
